-- ============================================================
-- 004_certificates.sql
-- TradeLens — Certificates table
-- Tanzania–Zambia Corridor | IIT Madras Zanzibar Campus, 2026
-- ============================================================
-- Depends on: 001_users.sql (public.users, country_code enum)
--             002_products.sql (public.products)
--             003_documents.sql (public.documents)
-- Referenced by: 005_verification_log.sql
-- ============================================================

-- ── Enums ────────────────────────────────────────────────────

CREATE TYPE certificate_type AS ENUM (
  'TBS',   -- Tanzania Bureau of Standards
  'ZABS'   -- Zambia Bureau of Standards
);

CREATE TYPE certificate_status AS ENUM (
  'active',
  'revoked',
  'expired'
);

-- ── Certificate number generator ─────────────────────────────
-- Format: TL-{issuing_country}-{certificate_type}-{6-char alphanumeric}
-- Example: TL-TZ-TBS-LK3M9A  (matches api-spec.yaml example)
-- Called at INSERT time; stored as an immutable column.

CREATE OR REPLACE FUNCTION generate_certificate_number(
  p_issuing_country country_code,
  p_certificate_type certificate_type
)
RETURNS TEXT AS $$
DECLARE
  v_suffix TEXT;
  v_number TEXT;
  v_exists BOOLEAN;
BEGIN
  LOOP
    -- 6 uppercase alphanumeric characters (A-Z, 0-9)
    v_suffix := upper(
      substring(
        replace(replace(encode(gen_random_bytes(6), 'base64'), '+', ''), '/', ''),
        1, 6
      )
    );
    v_number := 'TL-' || p_issuing_country::TEXT || '-' || p_certificate_type::TEXT || '-' || v_suffix;

    SELECT EXISTS (
      SELECT 1 FROM public.certificates WHERE certificate_number = v_number
    ) INTO v_exists;

    EXIT WHEN NOT v_exists;
  END LOOP;

  RETURN v_number;
END;
$$ LANGUAGE plpgsql;

-- ── Table ─────────────────────────────────────────────────────
-- One row per issued digital certificate (BR-01).
-- Linked to the source document, the trader, and the issuing officer.
-- SHA-256 hash and QR code URL are generated by certificateService.js
-- before the row is inserted.

CREATE TABLE public.certificates (
  id                  UUID                PRIMARY KEY DEFAULT gen_random_uuid(),

  -- Human-readable unique identifier — immutable after issue
  certificate_number  TEXT                NOT NULL UNIQUE,

  -- Relationships
  document_id         UUID                NOT NULL UNIQUE
                                          REFERENCES public.documents(id)
                                          ON DELETE RESTRICT,   -- never silently remove a certificate
  trader_id           UUID                NOT NULL
                                          REFERENCES public.users(id)
                                          ON DELETE RESTRICT,
  issued_by           UUID                NOT NULL
                                          REFERENCES public.users(id)
                                          ON DELETE RESTRICT,

  -- Certificate details
  product_name        TEXT                NOT NULL,             -- denormalised snapshot at issue time
  certificate_type    certificate_type    NOT NULL,
  issuing_country     country_code        NOT NULL,
  destination_country country_code        NOT NULL,
  valid_until         DATE                NOT NULL,

  -- Tamper detection (BR-01, BR-06)
  qr_code_url         TEXT                NOT NULL,             -- base64 PNG data URL
  sha256_hash         TEXT                NOT NULL UNIQUE,      -- SHA-256 of certificate payload

  -- Lifecycle
  status              certificate_status  NOT NULL DEFAULT 'active',
  revocation_reason   TEXT,
  revoked_by          UUID                REFERENCES public.users(id) ON DELETE SET NULL,
  revoked_at          TIMESTAMPTZ,

  -- Timestamps
  created_at          TIMESTAMPTZ         NOT NULL DEFAULT NOW()

  -- No updated_at: certificates are immutable after issue.
  -- Status changes (revoke/expire) are append-only via verification_log.
);

-- ── Constraints ───────────────────────────────────────────────

-- valid_until must be a future date at issue time
ALTER TABLE public.certificates
  ADD CONSTRAINT chk_valid_until_future
  CHECK (valid_until > CURRENT_DATE);

-- issuing and destination countries must differ (TZ↔ZM corridor)
ALTER TABLE public.certificates
  ADD CONSTRAINT chk_countries_differ
  CHECK (issuing_country <> destination_country);

-- certificate_type must align with issuing_country
-- TBS is issued by TZ, ZABS is issued by ZM
ALTER TABLE public.certificates
  ADD CONSTRAINT chk_cert_type_country
  CHECK (
    (certificate_type = 'TBS'  AND issuing_country = 'TZ') OR
    (certificate_type = 'ZABS' AND issuing_country = 'ZM')
  );

-- Revocation fields must all be set together or not at all
ALTER TABLE public.certificates
  ADD CONSTRAINT chk_revocation_consistency
  CHECK (
    (revoked_by IS NULL AND revoked_at IS NULL AND revocation_reason IS NULL)
    OR
    (revoked_by IS NOT NULL AND revoked_at IS NOT NULL AND revocation_reason IS NOT NULL)
  );

-- A revoked certificate must have status = 'revoked'
ALTER TABLE public.certificates
  ADD CONSTRAINT chk_revoked_status
  CHECK (
    (revoked_at IS NULL AND status <> 'revoked')
    OR
    (revoked_at IS NOT NULL AND status = 'revoked')
  );

-- trader_id must match the document's trader_id
ALTER TABLE public.certificates
  ADD CONSTRAINT chk_trader_matches_document
  CHECK (
    trader_id = (
      SELECT trader_id FROM public.documents WHERE id = document_id
    )
  );

-- ── Indexes ───────────────────────────────────────────────────

-- QR / ID lookup at border checkpoint — BR-03 (must respond < 30s)
CREATE INDEX idx_certificates_certificate_number ON public.certificates (certificate_number);

-- All certificates for a trader — GET /api/verify/trader/:trader_id (US-06)
CREATE INDEX idx_certificates_trader_id          ON public.certificates (trader_id);

-- Officer's issued certificates
CREATE INDEX idx_certificates_issued_by          ON public.certificates (issued_by);

-- Source document lookup
CREATE INDEX idx_certificates_document_id        ON public.certificates (document_id);

-- Status filter — active / revoked / expired
CREATE INDEX idx_certificates_status             ON public.certificates (status);

-- Expiry sweep — background job to flip active → expired
CREATE INDEX idx_certificates_valid_until        ON public.certificates (valid_until)
  WHERE status = 'active';

-- Combined: trader + status — used by compliance dashboard
CREATE INDEX idx_certificates_trader_status      ON public.certificates (trader_id, status);

-- SHA-256 tamper check lookup
CREATE INDEX idx_certificates_sha256             ON public.certificates (sha256_hash);

-- ── Auto-expire active certificates ──────────────────────────
-- Marks certificates as expired when valid_until < CURRENT_DATE.
-- Called by a scheduled job (e.g. pg_cron or GitHub Actions cron).
-- Safe to run repeatedly — only touches active, past-due rows.

CREATE OR REPLACE FUNCTION expire_certificates()
RETURNS INTEGER AS $$
DECLARE
  v_count INTEGER;
BEGIN
  UPDATE public.certificates
  SET status = 'expired'
  WHERE status = 'active'
    AND valid_until < CURRENT_DATE;

  GET DIAGNOSTICS v_count = ROW_COUNT;
  RETURN v_count;
END;
$$ LANGUAGE plpgsql;

-- ── Row Level Security (RLS) ──────────────────────────────────

ALTER TABLE public.certificates ENABLE ROW LEVEL SECURITY;

-- Traders can read their own certificates
CREATE POLICY "certificates_select_own_trader"
  ON public.certificates FOR SELECT
  USING (trader_id = auth.uid());

-- Standards Officers can read all certificates
-- (needed to avoid re-issuing against the same document)
CREATE POLICY "certificates_select_standards_officer"
  ON public.certificates FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM public.users
      WHERE id = auth.uid()
        AND role = 'standards_officer'
    )
  );

-- Customs Officers can read all certificates (border verification — US-05, US-06)
CREATE POLICY "certificates_select_customs_officer"
  ON public.certificates FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM public.users
      WHERE id = auth.uid()
        AND role = 'customs_officer'
    )
  );

-- Admins can read all certificates
CREATE POLICY "certificates_select_admin"
  ON public.certificates FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM public.users
      WHERE id = auth.uid() AND role = 'admin'
    )
  );

-- Only Standards Officers can insert (issue) certificates
CREATE POLICY "certificates_insert_standards_officer"
  ON public.certificates FOR INSERT
  WITH CHECK (
    issued_by = auth.uid()
    AND EXISTS (
      SELECT 1 FROM public.users
      WHERE id = auth.uid()
        AND role = 'standards_officer'
    )
  );

-- Standards Officers and Admins can update (revoke) certificates
-- No trader or customs officer may modify a certificate — ever.
CREATE POLICY "certificates_update_standards_officer"
  ON public.certificates FOR UPDATE
  USING (
    EXISTS (
      SELECT 1 FROM public.users
      WHERE id = auth.uid()
        AND role = 'standards_officer'
    )
  );

CREATE POLICY "certificates_update_admin"
  ON public.certificates FOR UPDATE
  USING (
    EXISTS (
      SELECT 1 FROM public.users
      WHERE id = auth.uid() AND role = 'admin'
    )
  );

-- Hard DELETE is never permitted — immutable audit trail (BR-06)
-- No DELETE policy defined; all roles are blocked at the RLS level.
